# Generated by Django 5.2.4 on 2025-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tasks_is_completed_tasks_priority_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('inprogress', 'in progress'), ('completed', 'complted')], default='pending'),
        ),
    ]
