# Generated by Django 5.2.4 on 2025-09-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_status_tasks_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
