# Generated by Django 5.2.4 on 2025-09-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tasks_is_due_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='hedader',
            new_name='hedder',
        ),
    ]
