# Generated by Django 5.2.6 on 2025-12-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_message_alter_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='task',
        ),
    ]
